### PR TITLE
Use ctags if ctags_cmd exists for filetype

### PR DESCRIPTION
**Pull request by smhc**

### CODE REVIEW

**Comment by liuchengxu** [comment]
Closing as this logic already exists. Thanks any way.

**Comment by smhc** [comment]
I think you misunderstood the change.

In my settings I have:

let g:vista_default_executive = 'vim_lsp'
let g:vista_ctags_cmd = {
       \ 'xyz': 'ctags --options=/ctags_opt -f - '
       \}

i.e I want to use vim-lsp as the executive by default. However, for 'xyz' files, there is no LSP available, so I use ctags with a custom command instead.

My change is about being able to open the vista side-bar with the correct executive for each file type (i.e just type :Vista without args).

An alternative solution is to have a filetype to executive map. However I figure if you have a custom ctags command for a particular filetype, you probably want to use the ctags executive.

**Comment by liuchengxu** [comment]
Thanks for the explanation. That makes sense, I love your idea. Could you please add some comment for this case?

**Comment by liuchengxu** [comment]
Merged, thanks!

**Comment by smhc** [comment]
Ok, I've added some comments. It is somewhat of a workaround. From the docs apparently Vista shoudl cycle through each of the executives until it finds one that returns data.

However when I use vim-lsp for an unsupported filetype I just get the error:
"Retrieving symbols is not avaliable"
I use vim-lsp with a 'whitelist' such that it only runs the LSP server for particular filetypes.

Either way - in addition to this change it might be worth a 'filetype to executive' map so that you don't need to configure ctags arguments, or might want ctags to be the default and vim-lsp to be the exception.

**Comment by liuchengxu** [comment]
That warning message is from:
https://github.com/liuchengxu/vista.vim/blob/a9c6bedf8433bff4b03b1ef780df6821f35a9afe/autoload/vista/executive/vim_lsp.vim#L89-L92

And it is indeed needless in this situation. I think we can modify the execute function to run without any check.

**Comment by liuchengxu** [comment]
@smhc  Can you see if [this branch](https://github.com/liuchengxu/vista.vim/tree/execute-without-check) works as you expected?

**Comment by smhc** [comment]
With that branch the error doesn't display any more.  However it doesn't automatically cycle through the executives when just using ":Vista" to open the sidebar.

It does cycle through when using ":Vista finder", however it does that with the master branch as well. I can raise a separate issue to track it properly.

**Pull request merged**
