### PR TITLE
Support getting the nearest symbol

### LINKED ISSUE #114: Show parent class with vista_nearest_method_or_function or add currentag function
Hi! Consider the following simple python file:
```python
class Foo:
    def __init__(self, x):
        self.x = x
````
If I place the cursor at `self.x` and run `:echo b:vista_nearest_method_or_function` I get an empty result whereas if I use Tagbar's `:echo tagbar#currenttag('%s', '', 'f')` I get `Foo.__init__()`. So my question is: is it possible to make `vista_nearest_method_or_function` more similar to Tagbar's `currentag`? Or introduce a new currenttag function that works like Tagbar's one. Thanks!!

### PR DESCRIPTION
**Pull request by liuchengxu**
Close #114

### CODE REVIEW

**Comment by petobens** [comment]
Can you try adding the parent when the current symbol is a member? i.e if I have a `foo.py` file with:
```python
class Foo:
    def __init__(self, x):
        self.x = x
```
and run `ctags foo.py` I get:
```
Foo	bar.py	/^class Foo:$/;"	c
__init__	bar.py	/^    def __init__(self, x):$/;"	m	class:Foo
```
I was wondering if  it's possible to use the `m class:Foo` part?

**Comment by liuchengxu** [comment]
The semantic of hierarchy in ctags is not well defined. I can't get the parent of some tag easily, see how the nested display is implemented in #58, which needs a lot of work. And I don't want to handle the case you post specially. So I would say it's impossible atm.

**Comment by petobens** [comment]
So there is no way to use the already implemented nested display hierarchy to achieve this? I mean at some point you do have a correct hierarchy from where you could retrieve the parent.

**Comment by liuchengxu** [comment]
That definitely needs some more work and I'm not motivated to implement it on my own.

**Comment by petobens** [comment]
Ok. Thanks anyway.

**Comment by petobens** [comment]
Mmm one minor thing: with the following file:
```python
class Foo:
    def __init__(self, x):
        self.x = x
```
When running `:echo vista#cursor#NearestSymbol()` I always get: `v:null`

**Comment by liuchengxu** [comment]
Can't reproduce. But it does return `v:null` if no symbol is found.

**Comment by petobens** [comment]
I think it's related to dein not properly loading the plugin: https://github.com/Shougo/dein.vim/issues/348

**Comment by liuchengxu** [comment]
hmm, just realized that it should be handled by vista.vim which should provide a full and independent  feature via `vista#cursor#NearestSymbol()`.

**Comment by petobens** [comment]
Ok. Do you want me to open a new issue for it?

**Comment by liuchengxu** [comment]
Feel free to do that in case I forget it.

**Pull request merged**
